version: "3.9"

services:
  web:
    image: next-about
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:3000"
    restart: unless-stopped
    # environment:
    #   NODE_ENV: development
